---
- name: Configure MacOS
  hosts: all
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
#    - role: geerlingguy.dotfiles
#      when: configure_dotfiles
#      tags: ['dotfiles']
#    - role: geerlingguy.mac.mas
#      when: mas_installed_apps or mas_installed_app_ids
#      tags: ['mas']
    - role: geerlingguy.mac.dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/kitty.yml
    - import_tasks: tasks/helix.yml
