roles:
  - name: sicruse.powerline-fonts
    version: v1.2.1
  - name: gantsign.oh-my-zsh
    version: 2.6.0
  - name: elliotweiser.osx-command-line-tools

collections:
  - name: community.general
  - name: geerlingguy.mac
